apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
      tag: latest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
        tag: latest
    spec:
      containers:        
      - image: workshoft/techtrends:latest
        imagePullPolicy: IfNotPresent
        name: techtrends
        ports:
        - name: liveness-port
          containerPort: {{ .Values.containerPort }}
          hostPort: {{ .Values.service.port }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: liveness-port
        readinessProbe:
          httpGet:
            path: /healthz
            port: liveness-port
