apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.image.repository }}
      tag: {{ .Values.image.tag }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.repository }}
        tag: {{ .Values.image.tag }}
    spec:
      containers:        
      - image: {{ .Values.image.author }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Values.appName }}
        ports:
        - name: liveness-port
          containerPort: {{ .Values.containerPort }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.httpGet.path }}
            port: liveness-port
        readinessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.httpGet.path }}
            port: liveness-port
