apiVersion: v1
appName: techtrends-staging
namespace:
  name: staging
service:
  port: 5111
  targetPort: 3111
  protocol: TCP
  kind: ClusterIP
image:
  author: workshoft
  repository: techtrends
  tag: latest
  pullPolicy: IfNotPresent
replicaCount: 3
resources:
  requests:
    memory: "90Mi"
    cpu: "300m"
  limits:
    memory: "128Mi"
    cpu: "500m"
containerPort: 3111
livenessProbe:
  httpGet:
    path: /healthz
    port: containerPort
readinessProbe:
  httpGet:
    path: /healthz
    port: containerPort
