apiVersion: v1
appName: techtrends
namespace:
  name: sandbox
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  kind: ClusterIP
image:
  author: workshoft
  repository: techtrends
  tag: latest
  pullPolicy: IfNotPresent
replicaCount: 1
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
containerPort: 3111
livenessProbe:
  httpGet:
    path: /healthz
    port: containerPort
readinessProbe:
  httpGet:
    path: /healthz
    port: containerPort
